### ISSUE TITLE
[Bug] Memory leak: Got the response to undefined request 9009

### ISSUE THREAD

**Issue by cv65kr** [temporalio/sdk-php#289]
### Describe the bug

"worker_exec: SoftJobError:\n\tsync_worker_exec_payload: LogicException: Got the response to undefined request 9002 in /src/vendor/temporal/sdk/src/Internal/Transport/Client.php:57\nStack trace:\n#0 /src/vendor/temporal/sdk/src/WorkerFactory.php(389): Temporal\\Internal\\Transport\\Client->dispatch(Object(Temporal\\Worker\\Transport\\Command\\SuccessResponse))\n#1

Looks like there is still a memory leak.

### Minimal Reproduction

Hard to find potencial issue, because it was discovered on production for couple days without redeployment. I am using almost all options available from SDK starting from SubWorkflows across to Search attributes.

My configuration

.rr.yaml
```
temporal:
    address: ${TEMPORAL_CLI_ADDRESS}
    namespace: ${TEMPORAL_NAMESPACE}
    cache_size: 100
    activities:
        allocate_timeout: 3600s
        num_workers: 9
        supervisor:
            max_worker_memory: 164

```

It's scaled horizontally 10 times by default.

I don't know how I can help you to find issue.

### Environment/Versions

- OS and processor: Linux
- Temporal Version: 1.18.1
- SDK - 2.3.2
- AWS
