### ISSUE TITLE
[Bug] cannot unmarshal array into Go struct field WorkerInfo.Flags of type map[string]string

### ISSUE THREAD

**Issue by root-aza** [temporalio/sdk-php#531]
### What are you really trying to do?

run worker php

### Minimal Reproduction

./rr serve -c .rr.temporal.dev.yaml

```yaml
version: "3"

metrics:
  address: 0.0.0.0:2116

status:
  address: 0.0.0.0:2115

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Vanta\Integration\Symfony\Temporal\Runtime\TemporalRuntime

rpc:
  listen: tcp://0.0.0.0:6001

temporal:
  address: "mdm_pos_temporal_server:7233"
  namespace: mdm
  activities:
    num_workers: 4
  metrics:
    driver: prometheus
    address: 0.0.0.0:2117
    type: "summary"


logs:
  level: debug
  channels:
    temporal.level: error
```

### Environment/Versions

RR 2024.2.1
temporal/sdk v2.11.2

### Additional context

Problem line https://github.com/temporalio/sdk-php/blob/master/src/Internal/Transport/Router/GetWorkerInfo.php#L85
