### ISSUE TITLE
[Bug] Can't run the tests of UpdateMethod

### ISSUE THREAD

**Issue by agpopov** [temporalio/sdk-php#577]
Hello, I want to test UpdateMethod in workflow. But I get an error:

```
AssertionError: assert($result !== null)
/var/www/html/vendor/temporal/sdk/src/Client/Update/UpdateHandle.php:128
/var/www/html/vendor/temporal/sdk/src/Client/Update/UpdateHandle.php:89
/var/www/html/vendor/temporal/sdk/src/Client/Update/UpdateHandle.php:75
/var/www/html/vendor/temporal/sdk/src/Internal/Client/WorkflowProxy.php:112
/var/www/html/tests/Workflows/UploadFileWorkflowTest.php:83
```

At the same time, the signal and jquery tests are working fine.

Here is the test code:

```php
public function testCanSaveFileData(): void
    {
        $this->testService->lockTimeSkipping();

        $arguments = [
            'path' => $this->faker()->filePath(),
            'original_name' => $this->faker()->word(),
            'extension' => $this->faker()->fileExtension(),
            'size' => $this->faker()->numberBetween(),
            'is_image' => $this->faker()->boolean(),
        ];

        $file = File::factory()->make($arguments);

        $workflow = $this->workflowClient->newWorkflowStub(UploadFileWorkflow::class);
        $run = $this->workflowClient->start($workflow);

        $this->assertEquals(WorkflowExecutionStatus::Running, $run->describe()->info->status);

        $result = $workflow->saveTempFileData(new SaveFileDataArguments($arguments));

        $this->assertEquals($file->id, $run->describe()->info->searchAttributes->getValue('FileId'));
        $this->assertEquals($file->toArray(), $result['data']);

        $this->testService->unlockTimeSkipping();
    }
```

I tried calling UpdateMethod via `update` and `startUpdate'. the result is exactly the same

**Comment by agpopov** [comment]
К сожалению, это я уже проверял. Воркеры запущены, workflow не падает.

Вот конфиг:

```yaml
version: "3"

rpc:
  listen: ${TEMPORAL_TESTING_HOST:-tcp://127.0.0.1:6001}

server:
  command: "php worker.php"

temporal:
  address: ${TEMPORAL_ADDRESS:-127.0.0.1:7233}
  activities:
    num_workers: 2

logs:
  level: info
  channels:
    server:
      mode: debug
      output: worker.log

kv:
  testing:
    driver: memory
    config:
      interval: 10
```

Вот код воркера:

```php

require 'vendor/autoload.php';
$app = require 'bootstrap/app.php';

$app->make(Kernel::class)->bootstrap();

$factory = WorkerFactory::create(
    rpc: new Goridge(Relay::create(config('testing.temporal.host'))),
    activityCache: RoadRunnerActivityInvocationCache::create()
);

$worker = $factory->newWorker(
    taskQueue: config('testing.temporal.queue'),
    interceptorProvider: new SimplePipelineProvider(
        app(InterceptorCollection::class)->toArray(),
    ),
);

$worker->registerWorkflowTypes(...config('orchestrator.temporal.workflows'));

foreach (config("orchestrator.temporal.activities", []) as $activityType) {
    $worker->registerActivity($activityType, fn(ReflectionClass $class) => app($class->getName()));
}

$factory->run();

error_log('stop worker');
```
